### ISSUE TITLE
Remove splash screen delay 

### ISSUE THREAD

**Issue by nounderline** [daimo-eth/daimo#1111]
Splash screen is manually hidden 300ms after sync either returns or throws:

https://github.com/daimo-eth/daimo/blob/e94ed904a4204ace5fc4d99c0133cbd87f389ac0/apps/daimo-mobile/src/sync/sync.ts#L42-L44

This increases time-to-interaction time by at least 1/3 of a second. We can make the app feel start up faster by showing UI immediately with [cached account data](https://github.com/daimo-eth/daimo/blob/e94ed904a4204ace5fc4d99c0133cbd87f389ac0/apps/daimo-mobile/src/logic/accountManager.ts#L99-L100) with visible sync indicator.

**Comment by dcposch** [comment]
Another way we could do this: hide right after the first render (eg useEffect on home screen) where the `lastUpdatedTime` is recent

this should be ~immediately after sync completes vs 300ms later
