### ISSUE TITLE
Prevent double notifications

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#1125]
prevent double notifs in case of two running instances

**Comment by nalinbhardwaj** [comment]
I just got double notified:

<img width="799" alt="image" src="https://github.com/daimo-eth/daimo/assets/6984346/d5fbef91-c6c7-457c-97e2-bd19614e0a47">
![IMG_859B104E6CF2-1](https://github.com/daimo-eth/daimo/assets/6984346/2f61c46a-1f5f-472c-95be-82e1c8d7f472)

**Comment by dcposch** [comment]
We already prevent push notifications until indexers are caught up = API server healthy.

However, we can't guarantee that there will only be one healthy API server at a time. During each deployment, there's a brief window where there are two.

## Proposed fix

- Create a new DB table for outbound push notifs
- Refactor push notifications to `INSERT ... IGNORE` into that table
- Only if this succeeds, send push to Expo
