### ISSUE TITLE
Unable to copy links from mac desktop app

### ISSUE THREAD

**Issue by andrewliu08** [daimo-eth/daimo#1255]
<img width="641" alt="Screenshot 2024-08-10 at 12 10 52 AM" src="https://github.com/user-attachments/assets/3fb09456-e6c2-4b35-ac2d-4192ea2b8d8e">

Clicking "Copy" here doesn't actually copy the link to the clipboard. When I right-click and then click "Paste" or click cmd+v, nothing gets pasted

**Comment by dcposch** [comment]
MacOS bug, unfortunately.
