### ISSUE TITLE
Tapping accept invite does nothing

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#1292]
User report:

> I tried to accept, but was having trouble getting the keyboard to move out of the way so I can see the invite code input, and now i'm in a state after "allowing paste" where tapping "accept invite" does nothing

The screen looking weird / oversized is likely due accessibility settings, not the end of the world. but the accept invite bug looks bad.

https://github.com/user-attachments/assets/0c97e12f-b732-4a5c-9f99-42a39447481a

**Comment by dcposch** [comment]
Hmm, @andrewliu08 & I just tried the following:

Daimo version: 1.9.7 

| Action | iOS | Android |
|--------|--------|--------|
| App closed, click valid invite link | Works | Works |
| App open, click valid invite link | Works | Works |
| Copy valid invite link, open app, tap accept | Works | Works |
| Copy invalid invite link, open app, tap accept | Works → enter invite | Works → enter invite |
| Copy valid invite code, open app, tap accept | Works | Works |
| Copy invalid invite code, open app, tap accept | Works → enter invite | Works → enter invite |

**Comment by dcposch** [comment]
@nalinbhardwaj can that user shake the phone + send debug log? I'm curious if they're on an old version of the app.

**Comment by dcposch** [comment]
Reproduced with an invalid deeplink.

Valid invite: (redacted, works)
Invalid invite: https://daimo.com/l/invite/invalid123 (correctly goes to Enter Invite screen)
Invalid link: https://daimo.com/l/t/%3Ctag? (from API error log > `getLinkStatus` failed > does not navigate to Enter Invite screen)

Immediate fix for the user: copy a valid invite code, try again > Accept Invite will work.

Fix for next app release in upcoming PR.
