### ISSUE TITLE
ENS avatar

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#147]
## Goal

Show faces on accounts to make them friendlier

## Possible solution

- add avatar to NameService
- ensure format is compatible with ENS avatars
- (later, when we make it an ENS subdomain, can expose it as a `avatar` record)
- display next to name when showing accounts
- also display ENS avatar next to ENS recipients

## Discussion

- Pro: friendlier, more human-looking app
- Con: increases impersonation risk
- Con: additional complexity, surface for potential slowness / flakiness

**Comment by nalinbhardwaj** [comment]
stretch add: support randomised generation (can be as simple as an emoji from a list) as the default profile pics, similar reasons for trust/confirmation.

**Comment by dcposch** [comment]
Closing

We can revisit rich profiles later, but ENS profiles specifically have substantial complexity and low adoption

More likely route for rich profiles is ability link {farcaster, etc}
