### ISSUE TITLE
Better link previews

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#159]
## Checklist

Before and after screenshots for each of the following:

- [ ] Telegram
- [ ] WhatsApp
- [ ] iMessage
- [ ] Signal
- [ ] Discord DM

### Telegram, logo way too big

<img width="500" alt="Screenshot 2023-08-15 at 2 41 36 PM" src="https://github.com/daimo-eth/daimo/assets/169280/3c42864a-cd0a-4c78-b651-0bdd1cc5e1f5">

### WhatsApp, black background

<img width="500" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/048abe34-8ec8-42f0-a091-e7a7fe420b49">

### iMessage, pretty good but logo too big

Size appears to be width-based. We can fix this by making the preview image landscape mode.

<img width="500" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/e4cf7bf6-3002-4d0e-922e-79cafdbe84d2">

### Signal, almost perfect. Logo could be slightly smaller.

<img width="500" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/42ab62b4-b5fb-4714-8107-55008326909b">

### Discord, aspect ratio too tall, dark background

<img width="500" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/99f21c9e-6c59-4a17-938a-ed0d14807b0a">

**Comment by dcposch** [comment]
## On-the-fly generated preview images

Warpcast generates link previews that look great. We currently just show a giant logo.

<img width="555" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/051e8a30-1af6-49be-b39b-4f2be1c39af7">

**Comment by michelle-chiu** [comment]
<img width="1170" alt="Screenshot 2024-01-22 at 5 36 04 PM" src="https://github.com/daimo-eth/daimo/assets/5884103/444832ed-1963-41a9-9e96-0045b56b9683">

Came up with a few designs for us in regards to request and payment links: https://www.figma.com/file/wBBNeEzlsObaE8A8i9iVf7/Mobile-App?type=design&node-id=3438%3A35366&mode=design&t=lOnsyqV2AfBAHmeI-1.
