### ISSUE TITLE
SendScreen layout broken on Android

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#188]
<img width=200 src="https://github.com/daimo-eth/daimo/assets/169280/b10b11b4-a7de-41f1-8fd1-ab5df9dd5b02" />
<img width=200 src="https://github.com/daimo-eth/daimo/assets/169280/534581fc-2ac0-4eb9-a557-3a4f2be941a8" />

- Send Payment Link floats above keyboard, hiding search results
- "Send via messaging app", "Cancelled by sender" should be centered

**Comment by nalinbhardwaj** [comment]
"Send Payment Link floats above keyboard, hiding search results" still seems to be an issue?
