### ISSUE TITLE
NameRegistry contract: add some admin/owner methods to revert username claims

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#231]
As a temporary stopgap for once we get to mainnet, we should probably add some ability to revert username claims by an admin account in case someone takes “vitalik” or tries to impersonate people.

Additionally, this unclaim can be restricted to only be possible within say 24 hours of the claim so we’re trust minimized beyond that. (seperately, ideally perhaps we should show something like “This account was recently registered” or “This is your first transaction with X” in UI for fresh accounts)

**Comment by dcposch** [comment]
done in #253
