### ISSUE TITLE
Key generation error on Pixel 3a

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#247]
## Summary

- v0.2.0 build 42
- Works for me on Pixel 3 running Android 12
- Failed for Steven on Pixel 3a running Android 12

<img width=220 src="https://github.com/daimo-eth/daimo/assets/169280/bdcd0ddd-0b14-49de-9de5-c17192cf1e86"/>

**Comment by dcposch** [comment]
## Investigation

Steven can't send debug log because you need to get past onboarding first. See #189 

- [x] Pixel 3 and 3a have different processors, Snapdragon 845 vs Snapdragon 670
- [ ] Use `forceWeakerKeys` on Pixel 3 + Android 12. Does that reproduce the error?
- [ ] Try with fingerprints disabled on Pixel 3

**Comment by nalinbhardwaj** [comment]
- [ ] for future debugging ease in case of the "weaker key failed" error we should put a send debug log button on that page too.

**Comment by dcposch** [comment]
fixed
