### ISSUE TITLE
Paymaster questions

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#259]
- why does setting a lower verificationgaslimit number fail rn?
- would be nice if the pimlico contract emitted an event when previousPrice is updated
- sub cent txes right now, but how accurate is it/how do updates etc get managed devops wise?

**Comment by dcposch** [comment]
- resolved
- asked Pimlico, they're working on it, no ETA
- resolved, real txs more like $0.05 to $0.10
