### ISSUE TITLE
Shorten deep links

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#262]
### Goal

Ansgar: the payment link URL is too long, looks scary.

#### Before

```
https://daimo.onrender.com/link/note/0x58d3A254a61D592BDEbcf1721e4e9263687AAB02#0xe2702055d60c3f39470a0fd322b85576215b5d34679f0c221534655220ee3af8
```

#### After

```
https://daimo.xyz/link/claim/123712#JibG5hFvh8a5QzB7nvZ
```

- Replace ephemeralOwner address with incrementing ID
- Replace private key with a shorter seed. Above, 14 bytes = 112 bits
- Base58-encode the seed

**Comment by dcposch** [comment]
### Request and account links

#### Before

```
https://daimo.onrender.com/link/request/28809824793486173/0x35DdE5723e36ceEb89bb8ff6206Bafb75D8a2Bd2/2
```

#### After

- Prefer Daimo account name or ENS name in <to>, instead of bare address. [De]serialize as EAccount

```
https://daimo.onrender.com/link/request/288/dcposch/2
```

- Optional to shorten request ID
  - Store nRequestsSent in app storage, doesn't have to be synced, purely local increment
  - Set `requestId = nRequestsSent * MAX_DEVICE_KEYS + thisDeviceKeySlot` which ensures no overlap.

**Comment by dcposch** [comment]
done (no base58; close enough).

**Comment by nalinbhardwaj** [comment]
Todo: base58, shorten as much as possible
