### ISSUE TITLE
Automate verification of deployed accounts on Etherscan

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#29]
Small UX improvement to verify newly deployed accounts on Etherscan. I think the best way to do this is to write a cron/listen for [`AccountDeployed`](https://goerli.basescan.org/tx/0x576376aafa9208434f51c0906b732ef9f56e6db087b6293bd7d0347177b2cb41#eventlog) events from the factory and use that to call the verify APIs (either via `forge` or `hardhat` etc.)

**Comment by dcposch** [comment]
I think we only have to verify a single one. Etherscan automatically verifies other contracts with identical code, right?
