### ISSUE TITLE
Touch base (no pun intended)

### ISSUE THREAD

**Issue by xdamman** [daimo-eth/daimo#34]
Hi there,

Just wanted to say hi from Brussels.
We stumbled upon your project and we are also working on a crypto wallet for non crypto people: https://citizenwallet.xyz

So wondering if there could be ways to team up (our plan is to develop this as an open source project like Metamask), or if it makes sense to keep two separate teams to focus on different use cases.

Let's do a call to chat more?
This is our [github](https://github.com/citizenwallet) and [our deck](https://deck.citizenwallet.xyz)

I'm reachable @xdamman on all platforms.

**Comment by dcposch** [comment]
Responded on tg. Citizen Wallet looks like an interesting project, good luck! GH issues are for bug reports and feature requests.
