### ISSUE TITLE
Mac app polish

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#374]
Amazingly, everything largely works out of the box on Mac via Catalyst.

https://apps.apple.com/app/daimo/id6459700343

## Remaining fixes

- [x] Scroll
- [x] Keyboard
- [x] Notifications
- [ ] Deep link > work if app is open in background, open to Home Screen if not
- [x] Window size not resizable / too small
- [x] Mac App Store listing "Not Verified for macOS"

Running on mac *did* show the initial account-created notification.
However, "Allow Notifications" fails with an exception.

See debug log: [debug-log-prod-app-mac.txt](https://github.com/daimo-eth/daimo/files/13203700/debug-log-prod-app-mac.txt)

[debug-log-prod-app-mac-deep-link.txt](https://github.com/daimo-eth/daimo/files/13203783/debug-log-prod-app-mac-deep-link.txt)

**Comment by nalinbhardwaj** [comment]
Keyboard and scroll issue seem like they are patched in react-native 0.65+ using pod file property `mac_catalyst_enabled` in our iOS pod file to apply them. Expo doesn't support setting that out of box so we should make a PR adding it to `expo-build-properties` package.

**Comment by dcposch** [comment]
Closing, I think we've fixed everything we can on our side. Can track https://github.com/facebook/react-native/issues/41447 separately.
