### ISSUE TITLE
Pull to refresh on Home

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#397]
Lot of users expect to be able to refresh the balance/transfer status by pulling the screen down on home when they're waiting for a transfer/just sent one. Show a loading spinner on swipe down and actually refresh. Calls [`resync`](https://github.com/daimo-eth/daimo/blob/master/apps/daimo-mobile/src/sync/sync.ts#L67C16-L67C22).

**Comment by dcposch** [comment]
done in #426
