### ISSUE TITLE
Account Page

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#440]
## Goal

Frequent request from devconnect user interviews:
- "This person just paid me, how do I pay them back?"

From Mike Neuder,
> feature request: i would love to be able to click on the name of someone who sent me a transaction to send them one in return
> also “per-user” txn history would be amazing
> like in venmo its called “between u”

## Proposed solution

![image_2023-11-18_12-57-16](https://github.com/daimo-eth/daimo/assets/169280/3a9ee96b-5e0b-49df-b074-eaac73da4219)

**Comment by dcposch** [comment]
cc @michelle-chiu

**Comment by michelle-chiu** [comment]
Added this to my design prioritization doc! [https://www.notion.so/daimo/Prioritization-Doc-f76c486afc6f4030929687114bb8a3e5?pvs=4](url)

Do we have a general idea of when we want these completed designs by?

**Comment by michelle-chiu** [comment]
Put together some early explorations here: [https://www.figma.com/file/wBBNeEzlsObaE8A8i9iVf7/Mobile-App?type=design&node-id=2403%3A14028&mode=design&t=3DdcG3iM3sI5mlTB-1](url). Happy to chat about it with @nalinbhardwaj sometime this week!

**Comment by dcposch** [comment]
done in #511
