### ISSUE TITLE
Error sending transaction / "hex data is odd-length"

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#461]
## Summary

I've seen the send errors several times recently--once for myself, once when onboarding a user, and here in the simulator:

<img width="422" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/bc7a10d2-b958-45b6-862b-5332694ff103">

At least one (and possibly all of them) caused by the following:

```
 ERROR  [SEND] error: Error: hex data is odd-length (argument="value", value="0x6f0F82fAFac7B5D8C269B02d408F094bAC6CF8771b6afe0f23ade4ca919870266257031d8aa1a32bb8227949047d089b3cad1fb0fb44628dc8224a9c07ba076f69c3f451ecce355ba57725602b53ac21dd2bc2a3a0000656440e6", code=INVALID_ARGUMENT, version=bytes/5.7.0)
 ```

**Comment by nalinbhardwaj** [comment]
fixed in https://github.com/daimo-eth/daimo/pull/468
