### ISSUE TITLE
Android: Handle system back button

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#464]
Currently, the system back button on android does not go through useExitToHome / useResetToHome, so if you're on the SendNav screen and press system back it quits the app entirely instead of redirecting to home. The back button handling for the top left button is already all in one place, so use that to override the system back button and make them both consistent everywhere.

https://github.com/daimo-eth/daimo/assets/6984346/c9a1c32f-22a6-4a7d-b1dc-92bc7bf4c76a

**Comment by dcposch** [comment]
done
