### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#486]
Create a splash screen for when the app is opened. Call sync during splash screen to refresh balance, tx history, paymaster ticket signature etc. and pre-render the home screen so it doesn't move around on load.

**Comment by dcposch** [comment]
Existing splash screen might be fine--we just have to keep it open until the sync completes or fails.

Notes on the sync:
- I recommend a short timeout (maybe 3s) for the initial sync
- If successful, splash screen disappears > home screen already shows up-to-date balance and history
- If failed, splash screen disappears > home screen already has the Offline header

**Comment by dcposch** [comment]
done #501
