### ISSUE TITLE
Add design improvements to align with Figma mocks

### ISSUE THREAD

**Issue by michelle-chiu** [daimo-eth/daimo#498]
<img width="691" alt="Screenshot 2023-12-04 at 3 53 23 PM" src="https://github.com/daimo-eth/daimo/assets/5884103/eea09ec9-00ee-461a-bc4a-0e7e60c385e1">

Happy to chat through the notes to explain any of the proposed changes further :)

Will be including a Figma link soon to reference most up-to-date designs to refer to.

**Comment by dcposch** [comment]
<img width="320" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/1986b21f-111e-474e-92b0-d7bedd1d804c">
hmm the height of the text is slightly smaller than the QR code icon
i can shrink it some more?

**Comment by dcposch** [comment]
## Bottom tab, suggested action updated

<img width="250" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/385fbafa-dc04-4a31-acc6-53b2880689fa">

**Comment by michelle-chiu** [comment]
@dcposch - Looking a lot better already, love the new improvements all around! ✨ 

Curious, what's the font size on the user's initial? It still looks slightly larger than it should be, but we're getting close!

**Comment by dcposch** [comment]
@michelle-chiu 24pt font

here's what it looks like with 20pt /22pt...

<img width="250" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/76600ad0-29f6-482a-858a-f23abb56a8ff"> <img width="250" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/e9ea7d26-fe8d-4c83-ac7c-ec163de0eaf6">

**Comment by michelle-chiu** [comment]
@dcposch Thanks for including screenshots of the other sizes—I don't mind sticking with 24px since the other sizes look too small. Can you increase the spacing between the notif and the search bar? Can be done in a separate PR.
