### ISSUE TITLE
Hold to Send should show Face ID / Touch ID Logo

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#508]
Often users express surprise when they weren't ready for it / prompted without a proper expectation.

Indicate that you are about to face-scanned / biometric scanned by putting a small icon for face scan/fingerprint on the confirm and send button.

Also nit, copy on the spinner during Face ID/transaction sending should say "Authorizing" instead of "Signing"

**Comment by wojtus7** [comment]
Hi @nalinbhardwaj @michelle-chiu!

I assume for iOS we use official Face ID and Touch ID icons but can you provide icon for fingerprint we want to use on Android phones, or we just leave it blank and show icons on iOS only?

**Comment by michelle-chiu** [comment]
@wojtus7 Great point, I'll add in the Android fingerprint button design. In the meantime, you can find the iOS design in the Figma file here (also seen in screenshot below): https://www.figma.com/file/wBBNeEzlsObaE8A8i9iVf7/Mobile-App?type=design&node-id=2429%3A7761&mode=design&t=0uRx6sxVzECzN6ib-1. 

<img width="264" alt="Screenshot 2023-12-14 at 1 48 43 PM" src="https://github.com/daimo-eth/daimo/assets/5884103/b8052802-fc77-460f-9ceb-bf07b6a7c15c">

**Comment by dcposch** [comment]
Done in #559
