### ISSUE TITLE
[Design] Navigation improvements

### ISSUE THREAD

**Issue by michelle-chiu** [daimo-eth/daimo#509]
Change the letter casing from all-caps to lowercase in the bottom nav menu

Current:
![IMG_5402](https://github.com/daimo-eth/daimo/assets/5884103/ed074723-7d41-4ced-a195-a5f91db1095b)

Ideal:
<img width="379" alt="Screenshot 2023-12-08 at 5 00 08 PM" src="https://github.com/daimo-eth/daimo/assets/5884103/b5b62406-005f-4f30-a6bc-025d12373824">

Figma link to reference: [https://www.figma.com/file/wBBNeEzlsObaE8A8i9iVf7/Mobile-App?type=design&node-id=2399%3A14612&mode=design&t=XOkV3aIxzP0rcTuc-1](url)

Icons do not need to be changed

**Comment by dcposch** [comment]
Done
