### ISSUE TITLE
[Design] Improvements to Settings Tab

### ISSUE THREAD

**Issue by michelle-chiu** [daimo-eth/daimo#510]
## Current
<img width="250" src="https://github.com/daimo-eth/daimo/assets/5884103/6970751c-03f8-4288-8c4a-12d26da87d95">

## Ideal
Minimizing the text size for "USDC • Base" and allowing users to "remove" devices
<img width="250" alt="Screenshot 2023-12-08 at 5 15 29 PM" src="https://github.com/daimo-eth/daimo/assets/5884103/85618398-ee2b-4678-9621-9794ab8d1593">

Figma Link for reference: https://www.figma.com/file/wBBNeEzlsObaE8A8i9iVf7/Mobile-App?type=design&node-id=2476%3A9086&mode=design&t=XOkV3aIxzP0rcTuc-1

**Comment by dcposch** [comment]
<img width="422" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/e0622063-f126-4b12-ba98-b4b03affda72">

What should we do about the THIS DEVICE tag?

**Comment by dcposch** [comment]
Might have to shorten the copy a bit to fit on small phones like iPhone SE.

<img width="452" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/95487ed7-2ca4-4eb2-9817-9b81e02e557c">

**Comment by michelle-chiu** [comment]
I liked the shorter copy you had in the existing version of the app! What do you think? 

<img width="338" alt="Screenshot 2023-12-11 at 3 17 07 PM" src="https://github.com/daimo-eth/daimo/assets/5884103/90af5054-c678-4c10-8b5c-329fbb8aec79">

**Comment by michelle-chiu** [comment]
Also, in regards to adding in more metadata here around "Device A" and "Device B," I see that Apple shares details around their devices' models. What do you and @nalinbhardwaj think are most applicable here? 

<img width="691" alt="Screenshot 2023-12-11 at 3 28 32 PM" src="https://github.com/daimo-eth/daimo/assets/5884103/9a38ef07-0a0f-4655-b67b-466a0e5bf7a5">

**Comment by michelle-chiu** [comment]
> <img alt="image" width="250" src="https://private-user-images.githubusercontent.com/169280/289641896-e0622063-f126-4b12-ba98-b4b03affda72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NDIzODYsIm5iZiI6MTcwMjQ0MjA4NiwicGF0aCI6Ii8xNjkyODAvMjg5NjQxODk2LWUwNjIyMDYzLWYxMjYtNGIxMi1iYTk4LWI0YjAzYWZmZGE3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwNDM0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDZmYTlkYzc3ZjIxZWNkNzFkN2FlMTY2ZTJhZGY3NjQ4MzBjNDBkMmQ0NWU2ZGQzMTE5NDU4YTVmM2MyZGEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tEM7zMdrcQEQ-W-QNWSZ1vz1lQtXuIEVAYqIOCfAEQ8">
> What should we do about the THIS DEVICE tag?

I like the "This Device" tag since it helps signify which device the user is on - let's keep it in the designs!

**Comment by dcposch** [comment]
<img width="500" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/27e82b1c-249e-4453-957d-eccba8fc9703">

**Comment by dcposch** [comment]
## `THIS DEVICE` - `Log out`
<img width="220" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/77d71edd-4dea-4909-aa1b-47473eed1401">

**Comment by dcposch** [comment]
## `Phone A` / `Phone B` -> `Phone` / `Phone 2` / ...

<img width="220" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/8f71ea4a-502a-41cb-8b20-d2596a4662ea">

**Comment by michelle-chiu** [comment]
@dcposch Let's move forward with the mock you have here removing the "add" date! "Log out" sounds good to me 👍 

![image](https://github.com/daimo-eth/daimo/assets/5884103/f6e0ed86-384a-4b2d-9a55-f798b08c0d7b)
