### ISSUE TITLE
Send failed, paymaster ticket already expired

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#512]
## Summary

A send failed with a bundler "expires to soon" error.

Error log:

```
{\"jsonrpc\":\"2.0\",\"id\":3318,\"error\":{\"message\":\"expires too soon\",\"code\":-32503}}" 
...
\"paymasterAndData\":\"0xedb395b8bd78788a57e3c8ed9b748f9cc29c28641b96a0f19e2e4955687d30d2d81dc59e71b47ca5a4453156a7a749d992d06ba78b0289641980347c76bea62f89f38370c97a0068c3d7dc2b74c06e1a7f436a8b0f00006571e7c0\",
```

Looking at the paymaster data, the validUntil is the last 6 bytes, 00006571e7c0
= 1701963712 unit time
= Thu Dec 07 2023 07:41 AM Pacific

this error posted today, Sat Dec 09 2023 15:57:05 Pacific

**This is likely from opening the app and sending immediately without a successful sync completing first, so no up-to-date paymaster ticket.**

## Proposed fix

Remove paymaster tickets altogether. We can use @nalinbhardwaj's `tx.sender` workaround to solve both this bug and save an extra ~70 bytes per op. See #506 follow-up section.

**Comment by nalinbhardwaj** [comment]
> This is likely from opening the app and sending immediately without a successful sync completing first, so no up-to-date paymaster ticket.

I think the splash screen change #486 would also help with this kind of issues going forward. We can add a follow-up to it to make it so we trigger splash screen if the user hasn't opened the app in a long time / has had it backgrounded for a long time

**Comment by nalinbhardwaj** [comment]
Fixed by paymaster change
