### ISSUE TITLE
Nav: easy way to cancel out of a flow

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#513]
## Goal

Currently, if I'm somewhere *within* the home tab, then tab over to Send and back to home, I'm back where I left off.

That seems fine... but there's no quick way to get back to the main home screen.

I find myself tapping home several times expecting to get there, and it doesn't work.

## Proposed fix

If I'm already on a tab and I tap that same tab again, it resets that tab to its home state.

CC @michelle-chiu lmk if you have an alternate solution

**Comment by michelle-chiu** [comment]
@dcposch In my original designs, I included a "x" icon on the upper-right hand corner of the screen to allow the user to exit back to the homepage (see screenshot)

<img width="371" alt="Screenshot 2023-12-10 at 10 25 46 PM" src="https://github.com/daimo-eth/daimo/assets/5884103/9b172624-f2f9-475b-a5bb-bfa10ed801ab">


What if we implemented your proposed fix and also the "x?"

**Comment by dcposch** [comment]
done in #536
