### ISSUE TITLE
Nav: easy way to dismiss keyboard

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#514]
Currently harder than I'd like, especially once you've selected the home screen search box.

I'm not sure of the best or most idiomatic way to fix it.

**Comment by michelle-chiu** [comment]
<img width="582" alt="Screenshot 2023-12-11 at 4 10 55 PM" src="https://github.com/daimo-eth/daimo/assets/5884103/d9a6ce4f-b41b-4a01-a662-6c6fe9979093">

What if we replaced the avatar with a back button icon (see screenshot)? @dcposch @nalinbhardwaj
