### ISSUE TITLE
Use Existing broken on testnet

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#539]
## Summary

Use Existing Account assumes mainnet.

If you try it from a testnet account:
- Testnet Alice scans Bob's (logged-out) phone.
- Testnet Alice successfully runs `addSigningKey` with Bob's device pubkey.
- Bob's phone stays on the QR screen forever, polling the mainnet API.

**Comment by nalinbhardwaj** [comment]
It’s not broken. Our testnet switch is in the invite page so to test testnet “Use existing” the expected flow is:
- go to create account > enter invite code “testnet”
- go back and switch to use existing flow

not ideal but tested it works
