### ISSUE TITLE
Deposit from Coinbase glitch

### ISSUE THREAD

**Issue by Gazzini** [daimo-eth/daimo#546]
Thanks for building Daimo, it's great!

I think this is likely a bug with Coinbase itself, and probably not with Daimo's integration.

When I press the "DEPOSIT FROM COINBASE" button, everything appears to work perfectly. However, on Coinbase's confirmation screen:

* Network shows as Base
* Fees look like ETH fees (should be 0.10 or free)
* Transaction is infinitely pending

<img width=250 src="https://github.com/daimo-eth/daimo/assets/1395751/520a5c3b-4af9-42dc-b898-2adc6af25357">

When I send USDC over BASE to the deposit address, even from Coinbase, everything works fine though.

**Comment by nalinbhardwaj** [comment]
Thanks for the detailed report @Gazzini, it does sound related to Coinbase itself, we’ll forward it to our contact in their team.

**Comment by dcposch** [comment]
### Diagnosis

I've reproduced the bug. **CBPay is incorrectly sending Base transactions on mainnet instead.**

#### Confirm send on Base. Suspiciously high fee.

<img width=250 src="https://github.com/daimo-eth/daimo/assets/169280/1ee195ed-c903-4a96-ae5a-0acff2ceee27">
<img width=250 src="https://github.com/daimo-eth/daimo/assets/169280/b9e39e86-a531-43e2-a104-ea31ee74e868">


#### Actual send occurs on mainnet.

https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48?a=0x4d350d99364634e07b01a9986662787dd3755f0a

**Comment by dcposch** [comment]
## Coinbase fixed the bug

re-enabling Coinbase Pay
