### ISSUE TITLE
Profile icons are inconsistent

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#550]
<img width="256" src="https://github.com/daimo-eth/daimo/assets/6984346/33b6c29a-630e-49a8-814a-a23a6e309a6d">

The proportions of A in the center icon vs in the tx list are different, makes it feel odd

**Comment by dcposch** [comment]
they were previously proportional

we made the letter smaller to match figma as spec'd here: #440

**Comment by dcposch** [comment]
from the last message in that thread i guess we can re-enlarge to 24pt. it still will not be exactly proportional

**Comment by nalinbhardwaj** [comment]
I see, I guess the reason I expected them to be consistent is because my mental model for them is as user profile pictures.

In future once we have custom profile pictures those will have to be consistent scaling of each other so I expected these to follow the same pattern. cc @michelle-chiu

**Comment by dcposch** [comment]
fixed. the icons match the figma exactly now--the reason it looked unproportional is bc the small ones, in the `HistoryList`, were too big.

<img width="250" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/72a2b581-a8e1-4090-ad4d-02c94b91c994"><img width="250" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/189ec244-f1ee-4d49-a616-9db2ebe7800a"><img width="250" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/8d423696-fd60-47b7-9122-5e9fcc9bb1ab">
