### ISSUE TITLE
[Design] Design improvements to transaction details (HistoryOpScreen)

### ISSUE THREAD

**Issue by michelle-chiu** [daimo-eth/daimo#553]
When a user taps on a transaction cell, a bottom sheet will appear with the transaction details. When the contact initial bubble is tapped on, they are sent to the "account page" (see screenshot): 

<img width="750" alt="Screenshot 2023-12-18 at 4 07 44 PM" src="https://github.com/daimo-eth/daimo/assets/5884103/4b3eb6af-caf0-40ce-8578-0cc2ac358f06">

Figma link: https://www.figma.com/file/wBBNeEzlsObaE8A8i9iVf7/Mobile-App?type=design&node-id=2521%3A16074&mode=design&t=uXCFjvTSz6zvIGbO-1

**Comment by dcposch** [comment]
## States

How do we handle the following states?

* Pending send. (I'm sending to Alice, but it's not in a block yet.)
* Fulfilled request. (I asked for $5, Alice fulfilled. Currently shows `Amount you requested`.)
* Send to link. (We need the `CANCEL LINK` button at the bottom, and potentially a way to send it again.)

**Comment by dcposch** [comment]
How to show sent vs received?

Currently in prod: `+ $1.00` vs `- $1.00`

In the mock it just says `Transfer` and then the amount

I'll try it with `Sent` / `Received`

**Comment by michelle-chiu** [comment]
@dcposch - I like your suggestions! Just modified the designs to reflect "sent" vs "received funds seen here:

<img width="730" alt="Screenshot 2023-12-26 at 3 50 23 PM" src="https://github.com/daimo-eth/daimo/assets/5884103/02bbff70-7eae-4d6b-88a0-5e161a85fbf0">

**Comment by michelle-chiu** [comment]
@dcposch In regards to handling these different states,

- Pending send. (I'm sending to Alice, but it's not in a block yet.)
- Fulfilled request. (I asked for $5, Alice fulfilled. Currently shows Amount you requested.)
- Send to link, not yet accepted. (We need the CANCEL LINK button at the bottom, and potentially a way to send it again.)

let me get back to you with updated designs either today or tomorrow

**Comment by michelle-chiu** [comment]
<img width="1099" alt="Screenshot 2024-01-09 at 2 15 26 PM" src="https://github.com/daimo-eth/daimo/assets/5884103/c05034a5-a801-40e0-b1a6-5edc22dc5db1">

Designs for: 
• Pending send. (I'm sending to Alice, but it's not in a block yet.)
• Fulfilled request. (I asked for $5, Alice fulfilled. Currently shows Amount you requested.)
• Send to link, not yet accepted. (We need the CANCEL LINK button at the bottom, and potentially a way to send it again.)
