### ISSUE TITLE
Nav: request tab doesn't reset

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#565]
Two related nav bugs:

- Create request > use share sheet to jump and successfully send > clicking cross takes you to home > swipe back to request tab is stuck on the screen:

<img width="256" src="https://github.com/daimo-eth/daimo/assets/6984346/74e113cd-10e1-4665-9db5-46a18366120c">

- Similar for incoming payment link claim, cross doesn't reset the request tab state so you're stuck in it. This one has a fix in https://github.com/daimo-eth/daimo/blob/d3dfacb579b73a95c1d30d9eb6e883aa5501a656/apps/daimo-mobile/src/view/screen/link/NoteScreen.tsx#L79 using `navResetToHome` instead, but seems like that function is going away in https://github.com/daimo-eth/daimo/pull/555/commits/ada6c175104b37aaf47f4125d5d845f12c7e8c19

**Comment by dcposch** [comment]
fixed in #567
