### ISSUE TITLE
Show error page for broken deeplinks

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#569]
## Goal

- User clicks a deeplink, opening Daimo.
- Deeplink is broken for any reason (typo, indexer issue, old version of the app, ...)

Current behavior: nothing happens. App ignores the deeplink.
**Goal: always respond to link. If necessary, show a helpful error.**

## Proposed solution

- Recognized link - nav as normal, then show error.
  - Account. Open the account screen. Potentially show account not found state.
  - Payment link. Open the note screen. Potentially show error.
  - Request link. Open the send screen. Potentially show error.
- Unrecognized link - show error modal bottomsheet in home tab. Show unrecognized link error. Link to app store to get latest version of app.

Design TBD.

**Comment by michelle-chiu** [comment]
<img width="936" alt="Screenshot 2024-01-05 at 6 11 00 PM" src="https://github.com/daimo-eth/daimo/assets/5884103/6ffa73ab-ebcf-42e0-b2c3-772f57db5b08">

Designs can be found here: https://www.figma.com/file/wBBNeEzlsObaE8A8i9iVf7/Mobile-App?type=design&node-id=2869%3A12606&mode=design&t=oOYJDxxTRRgghFsc-1

**Comment by michelle-chiu** [comment]
<img width="271" alt="Screenshot 2024-01-05 at 6 23 41 PM" src="https://github.com/daimo-eth/daimo/assets/5884103/c0065114-47fe-4fa3-9a62-d15bb3b7d499">

Also designed a bottom sheet version if we want to go in that direction instead

**Comment by dcposch** [comment]
done in #649

follow up to fix backdrop #691
