### ISSUE TITLE
Rich profiles

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#570]
## Goal

Main goal: give Alice confidence she's paying the right Bob, and not a different `bob`. 

Secondary goal: serve as a foundation for future growth / viral loop. Screenshots from the app look better.

Danger to avoid: don't facilitate impersonation. Signing a valid message from `vitalik.eth` is hard. Setting your display name and profile picture to match Vitalik's is easy. We should emphasize hard-to-fake rich profile info to achieve trust.

## Proposed solution space

**I think a good starting point is a Connect Wallet flow.** We can key a range of hard-to-fake rich profile information given a connected Ethereum address.

There's still a lot of design to figure out.

- **Connect Wallet**
  - How do we make a nice affordance to prove ownership of an ethereum account from Daimo? Can reference how Warpcast does it.
  - Do we use SiWE or just a raw message signature? 
  - How do we make it easy to sign from desktop? A lot of ethereum users don't have mobile wallets, and  mobile wallet UX remains terrible.
- **Once we have an eth address, what to show on account page?** (= `AccountScreen` when looking at someone else / `SettingsScreen` when looking at yourself.) There are many possible cases:
  - Address has no associated ENS name nor Farcaster profile. (One option is to not add anything to existing account screen in this case, and just a warning on settings screen = something like "You've linked your account 0x...1234, but no ENS or Farcaster found".)
  - Address has ENS. `ansgar.eth`.
  - Address has Farcaster. 
  - ...a big challenge: figure out how to visually differentiate / subordinate these to the main Daimo account display name. Paying Ansgar's Daimo account (where he linked ansgar.eth / proved he owns that account) is *not* the same thing as paying `ansgar.eth`. Unavoidably, it's possible for a user to end up looking at both of these account screens (ansgar with ansgar.eth linked vs ansgar.eth) and it's important they look distinct from each other. Can explain further if needed.
  - ...alternatively, we could show a *merged* account screen for (ansgar + linked ansgar.eth), with "Transfers between you" simply showing both. In this case, the `HistoryOpScreen` must clarify which one a particular transfer was to or from.

### References

https://www.interface.social
https://warpcast.com/dwr.eth/0x3b0d1fb0
https://warpcast.com/dcposch.eth/0xf8895746
Warpcast app link-eth-account screen

**Comment by nalinbhardwaj** [comment]
### Connect to Twitter

Flow: Sign a unique message → Tweet a unique link / identifier on twitter, ideally with an invite link → Connection shown on Daimo profile.

Creates a great identity link for "crypto twitter" folks and a number of apps have created very successful viral loops by leeching twitter like that.

**Comment by michelle-chiu** [comment]
<img width="1066" alt="Screenshot 2024-01-08 at 5 33 18 PM" src="https://github.com/daimo-eth/daimo/assets/5884103/771b2494-adb7-4474-8fa0-22dc2771905b">

Designs include:
1. **Skippable onboarding screens** to connect wallet during sign-up
2. **Account/profile page design** with new metadata (see requirements)
3. **Homepage notification** that asks users to connect wallet (if haven’t already done so)
4. **UX flow** if a user decides to connect wallet post-onboarding (i.e. via account/profile page or notification)
5. **Search page** (what will we show in the search bar?)

Final designs can be found here:
https://www.figma.com/file/wBBNeEzlsObaE8A8i9iVf7/Mobile-App?type=design&node-id=2869%3A11238&mode=design&t=jh5fLaOZMROgY1AR-1

**Comment by dcposch** [comment]
## Splitting this out

In rough order:

- [ ] #734
- [ ] Rich profiles / connect Twitter
- [ ] Rich profiles / connect Telegram
