### ISSUE TITLE
biometric icon should be shown at all places where user is about to be Face IDed

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#580]
currently only in send payment flow, needs to be added anywhere where the button is upstream of `useSendAsync`, `expo-passkeys`, `expo-enclave`.

non-exhaustive list:
- send payment link
- reclaim payment link
- add new device
- remove device
- create backup
- onboarding generate screen on android

**Comment by dcposch** [comment]
done in #736
