### ISSUE TITLE
Android Hold to Send is flaky

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#591]
From Adhyyan: Hold to send is flaky, loads fully but doesn’t do anything, have to do it 3-4 times to make it work

On Android 33, 1.4.5 Build 91

<img width="256" src="https://github.com/daimo-eth/daimo/assets/6984346/348cf283-dc00-4f03-bcda-73c08a33b5a4">

Can’t replicate on my Pixel 3 Android 31 :(

**Comment by nalinbhardwaj** [comment]
fixed by updating? still worth investigating

**Comment by dcposch** [comment]
fixed in #603
