### ISSUE TITLE
Request Tab clarity

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#596]
## Goal

Make it obvious to users that they can request money from anyone by sending a link. 

#### Current screen is non-descriptive

<img width="230" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/d3202ffc-68f4-46b0-8e3c-0079384ee59f">

Easy to assume that you can only send requests to other Daimo users --it's not obvious you're creating a link.

#### Proposed addition

Copy, possibly in an info bubble, along the lines of:

> **Send a request link.** Request USDC from someone using any messaging app.

**Comment by michelle-chiu** [comment]
<img width="897" alt="Screenshot 2024-01-11 at 1 16 30 PM" src="https://github.com/daimo-eth/daimo/assets/5884103/8c98f07b-78c5-443f-9d64-5db9073f7b65">

Designs can be found here: https://www.figma.com/file/wBBNeEzlsObaE8A8i9iVf7/Mobile-App?type=design&node-id=2898%3A14732&mode=design&t=1ZkadxeIKUJZCyAl-1

**Comment by dcposch** [comment]
done in #641
