### ISSUE TITLE
Devices and Backups one-pagers

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#612]
Current pages are very bland / single button, add explainers in the apple style:

<img width="256" src="https://github.com/daimo-eth/daimo/assets/6984346/280de241-201d-4cce-bb30-7191a0dc005a" /> <img width="256" src="https://github.com/daimo-eth/daimo/assets/6984346/cb77ee95-1cf3-4a97-9a64-05691ae02826"/>

**Comment by michelle-chiu** [comment]
<img width="584" alt="Screenshot 2024-01-12 at 4 06 53 PM" src="https://github.com/daimo-eth/daimo/assets/5884103/aeac7239-2c2a-4936-9876-4099aef7aebc">

I spoke to Nalin and thought this design would be better suited by saving a "click" and showing the description and educating the user upfront.

Design can be found here: https://www.figma.com/file/wBBNeEzlsObaE8A8i9iVf7/Mobile-App?type=design&node-id=3093%3A13238&mode=design&t=vuAPL0S91gfKm3HU-1

**Comment by nalinbhardwaj** [comment]
Copy suggestion:

> **Create a Backup**
> Safely store a passkey in your password manager

> **Add a Device**
> Use your Daimo account on another device

**Comment by wojtus7** [comment]
Hi @michelle-chiu Can I download new icons anywhere in svg version or png for both blue and gray version? 

As far as I can see from Figma I can download only icons visible on design so four gray icons and settings icon in blue version ;-;

**Comment by nalinbhardwaj** [comment]
@wojtus7 we will skip the icon update for now / not part of this issue. We are currently in the process of exploring new branding so will change soon. Thanks!
