### ISSUE TITLE
Tap-to-pay NFC card checkout

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#614]
## Goal

Make it easy for people to pay point-of-sale with Daimo.

Given that iPhone doesn't currently let apps access the HCE (host card emulation) capability, doing this between the app and a normal NFC reader is not possible.

## Proposed solution

@nalinbhardwaj found a great NFC card vendor. Taps work fast, and at a good distance!

**We can make cards where tapping takes you to a checkout page.** Then, you can pay with Daimo with one tap.

Open work:
- [x] **Checkout link.** Should be as short as possible, eg `https://daimo.com/r/A38fkWz`
  - For prototype, this can redirect to a static Daimo deeplink, either account or request. Further iteration can make it dynamic, driven by a point-of-sale webapp on seller side.
  - Open question: if site redirects to deeplink, does this automatically open the app? Or does user stay in browser? In second case, we'll need to make the checkout link a deeplink directly.
- [ ] **Card design.** We can start with one for the RWE event. cc @michelle-chiu

**Comment by nalinbhardwaj** [comment]
> Open question: if site redirects to deeplink, does this automatically open the app? Or does user stay in browser? In second case, we'll need to make the checkout link a deeplink directly.

Just tested by making a 301 redirect, it sends that exact link to the app, not the redirected version. I think we would just need to make the fetch and redirect work in app.

**Comment by michelle-chiu** [comment]
Card designs I developed today in an art deco style—I'm happy if we decide to move forward with any of the concepts shown here: 
<img width="1398" alt="Screenshot 2024-01-12 at 5 25 09 PM" src="https://github.com/daimo-eth/daimo/assets/5884103/80d6887f-ed70-4546-b49d-ad850aa40e30">


Figma link: https://www.figma.com/file/wBBNeEzlsObaE8A8i9iVf7/Mobile-App?type=design&node-id=2311%3A3&mode=design&t=vuAPL0S91gfKm3HU-1

**Comment by michelle-chiu** [comment]
Design update: 
• Switched to vertical orientation
• Added in a tap-to-pay logo via Nalin's suggestion

<img width="952" alt="Screenshot 2024-01-15 at 11 55 19 AM" src="https://github.com/daimo-eth/daimo/assets/5884103/0115d22c-8f2e-4041-8964-302bdef022b2">

Link to design concept in Figma: https://www.figma.com/file/wBBNeEzlsObaE8A8i9iVf7/Mobile-App?type=design&node-id=2311%3A3&mode=design&t=xdzT3bv4OEoiMHh9-1

**Comment by dcposch** [comment]
Done in #617
