### ISSUE TITLE
Onboarding Redesign

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#615]
Collecting some ideas:
- Communication
    - explain USDC, rollups: global, snappy, secure
    - Explain self custody and device keys succinctly and well:
        - vault animation, this is your responsibility, you can't call customer support, on your device only, key can't ever leave device, no one else has access, there's no bank
        - https://github.com/daimo-eth/daimo/pull/606#discussion_r1449390992
        - another analogy we could lean into is how WhatsApp shows key rotations in chat
- Transitions
    - Make it feel progressive and fast
    - Progress bar
        - Family has a nice style: 
        - <img width="256" src="https://github.com/daimo-eth/daimo/assets/6984346/9b2c7eb6-cccc-4fce-a585-bc30c84c023f">
 - Illustrations
     - Icons feel very dated, use custom/more beautiful illustrations, maybe more color?
- lot of people don't swipe through the intro pages, perhaps convert it to something like #612 to make it a single pager and short copy like the landing page https://daimo.com
- Existing account flow improvement
    - If you select restore from backup, we should stop showing the QR code at the top and make it clear to the user what's currently being done. Related: #613 
- invite code / paste link screen
    - on valid invite show sender profile picture etc
    - lean more on social proof, show other users in extra bottom space
- use existing screen
    -  improve copy for add device scan so people don't use regular QR reader
- don't increment phone number during add device
- https://github.com/daimo-eth/daimo/issues/619
- others...?

**Comment by dcposch** [comment]
## Onboarding upgrade

We saw some people in Denver get stuck in onboarding. Fixing:

https://www.figma.com/file/wBBNeEzlsObaE8A8i9iVf7/Daimo-iOS-App?type=design&node-id=4100%3A23944&mode=design&t=HrG5MaVLUj9fUy70-1

**Comment by michelle-chiu** [comment]
<img width="1123" alt="Screenshot 2024-03-25 at 10 53 43 AM" src="https://github.com/daimo-eth/daimo/assets/5884103/c948c8d9-4ce1-4a9f-8cc3-038a51a78210">

Designs can be found here: https://www.figma.com/file/wBBNeEzlsObaE8A8i9iVf7/Daimo-iOS-App?type=design&node-id=4347%3A1024&mode=design&t=QNNGjXRO5uHOykJn-1

**Comment by dcposch** [comment]
Done in #988
