### ISSUE TITLE
Compose improvements

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#644]
- iOS with Mail removed: "Reinstall Mail" prompt
- Non-Pixel Androids: showing share sheet instead of prefilled email/sms

**Comment by nalinbhardwaj** [comment]
> iOS with Mail removed: "Reinstall Mail" prompt

Looks like the best solution is to use [react-native-email-link](https://github.com/includable/react-native-email-link) instead

**Comment by dcposch** [comment]
Works after reinstalling Mail > setting Gmail as default

**Comment by nalinbhardwaj** [comment]
I think these are reasonably fixed for now -- Non-Pixel Androids fixed afaik, iOS with Mail removed fixed if default is set "correctly". Unassigning but leaving open in case we want to do react-native-email-link in future.
