### ISSUE TITLE
Link formatting bug: https://.../daimo:/...

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#657]
## Summary

Version: 1.5.0
Platform: macOS

![image](https://github.com/daimo-eth/daimo/assets/169280/f5d23db9-f2f4-461a-9e8f-311b077f3d24)

**Comment by nalinbhardwaj** [comment]
This was because the user (invitee) used an old version of the app but a new version of the link from the inviter. Closing since it’s very low priority to make the error look better in that case.
