### ISSUE TITLE
Android 1password / password manager support

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#663]
## Goal

European users typically have Android & sometimes custom (non-GPM) password managers. Eg:

> Just onboarded my girlfriend today actually, the only thing that came up was her wanting to use her usual password manager for the backup

- Android
- 1password

**Comment by nalinbhardwaj** [comment]
Not on us, Android `CredentialManager` only supports third party password manager passkeys on Android 14 and up.

**Comment by nalinbhardwaj** [comment]
Not on us, Android CredentialManager only supports third party password manager passkeys on Android 14 and up. Closing this as won't fix for that reason, feel free to re-open if you meant something different.
