### ISSUE TITLE
Restrict window size (or set smaller initial sizes) on Mac app

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#671]
The overall app looks weird when the width of window is too large.

Two fixes, not sure how doable/possible each one is:
1. Set launch window size to be smaller/something like the usual iOS phone dimensions. Telegram app does this nicely by opening at ~420x650 dimensions on my computer:
<img width="240" alt="image" src="https://github.com/daimo-eth/daimo/assets/6984346/1b88581f-210c-4178-acf3-5fe5ab26b53e">

2. Restrict app window from being resized
3. If 2 is not possible, maintain aspect ratio of phones on resizing if possible.

Pulled out from #668

**Comment by dcposch** [comment]
fixed in #721
