### ISSUE TITLE
Website rebrand

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#702]
## Goal

**Rebrand https://daimo.com**. NextJS, largely static site, few code changes, mostly style changes.

### Before > after

<img width="1413" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/bbf76bf9-cc06-403c-ab88-e63004091ffe">

Code: see `apps/daimo-web` 
New design: see Figma mocks below

## Approximate steps

- [ ] Clone repo. Follow quickstart to run `daimo-web` locally, pointing to our hosted testnet API.
- [ ] Update homepage. (See https://daimo.com/ ) See mocks below. Prioritize clean, simple code. If anything in mocks is pulling you in direction of greater complexity, we can discuss in chat.

**Comment by michelle-chiu** [comment]
<img width="1605" alt="Screenshot 2024-02-12 at 11 49 56 AM" src="https://github.com/daimo-eth/daimo/assets/5884103/528f19f6-ae85-4e3c-a81f-3e02f7267517">

Figma link can be found here: https://www.figma.com/file/KKzdrpm6obI7IjmhgKG3dz/Branding?type=design&node-id=461%3A20942&mode=design&t=cybmVWULzkRpDJ3p-1

**Comment by michelle-chiu** [comment]
On load animations: 

Desktop:
https://github.com/daimo-eth/daimo/assets/5884103/00bfe890-97fb-41b0-a468-8daf30c4b0b9

Mobile: 
https://github.com/daimo-eth/daimo/assets/5884103/1503e21b-dcf7-4319-ae51-2740e8335356

**Comment by michelle-chiu** [comment]
Final designs can be found in this new Figma file: 
https://www.figma.com/file/3HKkiP8QQ5CnBq1BH3mbzz/Website?type=design&node-id=1%3A82&mode=design&t=kktRONK2LiswLFfL-1

<img width="1196" alt="Screenshot 2024-02-19 at 12 22 02 PM" src="https://github.com/daimo-eth/daimo/assets/5884103/3210bff2-c434-4aa6-b85d-08e3cf7c347c">

**Comment by ItsApex** [comment]
I can hop on this 

here are few projects 
https://linkcollect.io/
https://zedit.io/

And there are few apps we are working in based out of UK
Would love to craft this one as well :)

**Comment by dcposch** [comment]
@ItsApex thanks for the offer. Found someone!

**Comment by dcposch** [comment]
@ItsApex thanks for the offer. Found someone already!

**Comment by dcposch** [comment]
Done in #740
