### ISSUE TITLE
App Rebrand

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#732]
## Goal

Update the app to match our new brand. Green theme color. Feels more international.

## Parts

- [ ] Logo
   * Splash screen, app icon, etc.
   * cc @michelle-chiu for these assets
- [ ] App colors and styles
- [ ] Bottom tab icon #399 
  * cc @michelle-chiu for center

**Comment by michelle-chiu** [comment]
**Splash screen:** 
![splash-screen](https://github.com/daimo-eth/daimo/assets/5884103/1b82877b-2a6d-41aa-a686-ee774f1a2621)

**Comment by michelle-chiu** [comment]
New homepage color: #14B174

![homepage](https://github.com/daimo-eth/daimo/assets/5884103/1ae7a57f-c776-41cc-8b55-4750a2fa0a6b)

**Comment by michelle-chiu** [comment]
Figma file to designs: https://www.figma.com/file/KKzdrpm6obI7IjmhgKG3dz/Branding?type=design&node-id=927%3A11710&mode=design&t=Q98BezyLKUV1ZmpY-1

**Comment by wojtus7** [comment]
Oooooh one more thing I just realized: Can I find somewhere color that is called `primaryBgLight` in the code.
In the user interface it is for example used as highlight for tapped buttons.

What interesting this is a standard hex without opacity `#aaccff`. Usually I would do something like `#14B174aa` to add some opacity but in this case I'm just asking for color to be sure we are backward compatible

![image](https://github.com/daimo-eth/daimo/assets/42337257/c76b27a8-c713-4db3-8896-33e2d65b81a7)

**Comment by michelle-chiu** [comment]
> @michelle-chiu can I get svg or pngs for daimo logo used in bottom tab? Looks like I can't export it from Figma :< <img alt="image" width="236" src="https://private-user-images.githubusercontent.com/42337257/306670612-7fbe80d9-3afb-4e06-b77b-0e5839245f3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDM3NjQsIm5iZiI6MTcwODU0MzQ2NCwicGF0aCI6Ii80MjMzNzI1Ny8zMDY2NzA2MTItN2ZiZTgwZDktM2FmYi00ZTA2LWI3N2ItMGU1ODM5MjQ1ZjNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE5MjQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMTJjYmQ2NDM1ZTQ0NzExOGNiMDc2Yjk5ZDkzMmY2MTk1MjNkYzliNGY1NjI5NTM4NGZjZjEzNjE3N2FiOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2UsKNo7Rl_CCyRDesvowWLfyoggUja5V-SFVxp0o6qg">

Hey Woj, here are SVG files for the active and unactive logo buttons: 

![daimo-logo-active](https://github.com/daimo-eth/daimo/assets/5884103/dcb762c0-80e3-418c-a278-29b8bec10ac2)

![daimo-logo-unactive](https://github.com/daimo-eth/daimo/assets/5884103/20c11e44-4381-4fb0-8bed-fa2c7912d6c5)

**Comment by michelle-chiu** [comment]
> Also can I get icon logo with shadow on transparent background and background as separate sprites to create android `adaptive icon` foreground and background?

Here is the logo with shadow on transparent bg and the background:
![Logo](https://github.com/daimo-eth/daimo/assets/5884103/0

![app-icon](https://github.com/daimo-eth/daimo/assets/5884103/2bb1daf0-259a-4667-8960-5a76b08cf440)
21c3d9b-eb80-4412-a7ef-fcc2c7ab552c)

**Comment by michelle-chiu** [comment]
> Oooooh one more thing I just realized: Can I find somewhere color that is called `primaryBgLight` in the code. In the user interface it is for example used as highlight for tapped buttons.
> 
> What interesting this is a standard hex without opacity `#aaccff`. Usually I would do something like `#14B174aa` to add some opacity but in this case I'm just asking for color to be sure we are backward compatible
> 
> ![image](https://private-user-images.githubusercontent.com/42337257/306692223-c76b27a8-c713-4db3-8896-33e2d65b81a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDQzNDgsIm5iZiI6MTcwODU0NDA0OCwicGF0aCI6Ii80MjMzNzI1Ny8zMDY2OTIyMjMtYzc2YjI3YTgtYzcxMy00ZGIzLTg4OTYtMzNlMmQ2NWI4MWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE5MzQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZmIzOTgwOTlhNDk5ZWE2Y2YwYjczYWFhN2JkYmU4NWE4NGZiNTE2OTc1NDI4NjNiNjRhYjE5MjkxMjMwMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MiQttgWSzUnnUekJJQg3f7gFFvuXqZFjvzAmwIZeWqk)

In regards to the codebase, this may be a better question for @nalinbhardwaj (?)

**Comment by wojtus7** [comment]
Ahh @michelle-chiu sorry I wasn't clear, my bad 🫠
I'm just asking what new colour to use under pressed buttons etc because I can't find it in figma 😞
![image](https://github.com/daimo-eth/daimo/assets/42337257/14015344-5265-4228-83fb-eec4d1a7f0b5)

**Comment by michelle-chiu** [comment]
> Ahh @michelle-chiu sorry I wasn't clear, my bad 🫠 I'm just asking what new colour to use under pressed buttons etc because I can't find it in figma 😞 ![image](https://private-user-images.githubusercontent.com/42337257/306764705-14015344-5265-4228-83fb-eec4d1a7f0b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDc2NjQsIm5iZiI6MTcwODU0NzM2NCwicGF0aCI6Ii80MjMzNzI1Ny8zMDY3NjQ3MDUtMTQwMTUzNDQtNTI2NS00MjI4LTgzZmItZWVjNGQxYTdmMGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDIwMjkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3M2UyNjVhNjc0ODJlY2M4NmM2MDkyYzhkNWJkOGU3OGUwNjdiYjA2NjQ2MTRiYWM3MDFhMzVmN2EzYTFiMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gEjLzyO-ul8eHtEB-21SP_YpGb6QGOAPOcLwv6L5YNg)

Ah I see, let's go with the color #CCF3D7! Here's a screenshot of what it should look like: 

<img width="385" alt="Screenshot 2024-02-21 at 12 57 45 PM" src="https://github.com/daimo-eth/daimo/assets/5884103/3c8fcea1-5415-4289-9b74-be94cff3efbd">

Let me know if there's anything else
