### ISSUE TITLE
gas optimise sig validation

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#8]
low hanging fruit: pass the index of the key as call data (maybe just append a byte to the signature?) directly instead of looping the whole list (and eating the computation cost of wrong verifies)

https://github.com/daimo-eth/daimo/blob/cecc98ec2286f00f8f0a547b083c400cae75d073/packages/contract/src/Account.sol#L111-L115

**Comment by dcposch** [comment]
we can get below 100k gas per verification just using #64
