### ISSUE TITLE
Make "invited by" click transition smooth

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#801]
## Current

https://github.com/daimo-eth/daimo/assets/6984346/ff975f36-d34f-4cc6-aa0e-4c2441e5b650

## Expected

- Pressing inviter makes a smooth transition from right to left like native screens
- Pressing the back button on the inviters profile takes you to the invitees profile with clean transition

## Fix

Use native stack navigator to push the new profile so it loads with a clean transition + preserves back button to take back to the previous profile rather than exit completely.

**Comment by dcposch** [comment]
Fixed in #803
