### ISSUE TITLE
Link previews: show linked profile, show link status

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#816]
## Goal

We want to post links--in particular, request links--to Farcaster. People should see at glance what state the link is in.

* The link preview should show linked profiles
* The link preview for pending, fulfilled, and cancelled requests should look different

## Proposed implementation

**We'll have to add a cache-buster to the link in order to achieve clean previews.** Eg `/l/request?...&s=complete` ; the identical link, posted again, will get previously-cached (= wrong) preview images.

Current example:

https://daimo.com/l/request/daimo/4/60292611670329437

**Comment by kayleegeorge** [comment]
For the request preview: `/l/r/nibnalin/6/DA1AVbUiEdbvNfb3J7G2Ve`

**Before**:
<img width="525" alt="Screenshot 2024-06-03 at 4 37 35 PM" src="https://github.com/daimo-eth/daimo/assets/62825936/fbf2c8ba-0bd6-4bb2-98b2-07713ee60e10">

**After**:
<img width="605" alt="Screenshot 2024-06-03 at 4 36 25 PM" src="https://github.com/daimo-eth/daimo/assets/62825936/a4be0277-8f5f-47e0-bb2b-c8362f6a8808">

**Comment by kayleegeorge** [comment]
added profile pictures with: https://github.com/daimo-eth/daimo/pull/1107
