### ISSUE TITLE
Farcaster @daimobot

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#817]
## Summary

Make it easy to pay people and get paid on Farcaster.

Now that we have Farcaster integration, we can implement `@daimobot` to facilitate.

#### Alice has FC linked, wants to request payment

> Alice posts `@daimobot request $25`
> Daimobot responds with a request link, with Alice as recipient
> As soon as it's paid or cancelled, Daimobot responds again with the update

* The link preview should show linked profiles
* The link preview for pending, fulfilled, and cancelled requests should look different
See https://github.com/daimo-eth/daimo/issues/816

#### Alice has no FC link, wants to request

> Alice posts `@daimobot requests $25`
> Daimobot posts asking her to link her Farcaster in Daimo
> As soon as she does that, Daimobot responds again with the request link
> After that, same as above

#### Alice wants to pay someone

> Alice responds to Bob's post with `@daimobot pay $20`
> Daimobot responds with a request link, with Bob as the recipient
> (If Bob doesn't have FC linked, posts asking Bob to link his FC. If Bob has a .eth linked, then can post a request link with bob.eth as the recipient, eg `Great, send $20 to bob.eth <link>`)
> Otherwise, same as above.

In future versions, we can add memos/notes to the requests and do other fancy versions

**Comment by nalinbhardwaj** [comment]
Frontend mock:

![daimobot-frontend-2](https://github.com/daimo-eth/daimo/assets/6984346/6194ad5b-5ce1-4ae6-93f5-c68e86791221)

MVP: simply links to a request page, example: https://daimo.com/l/request/daimo/4/60292611670329437

V2: Puts a frame in the OG of all request pages, making them easy to post to Farcaster and be fulfilled.

**Comment by dcposch** [comment]
##  Possible extension: sending or paying without replying

**Alice wants to pay someone**
> Alice casts `@daimobot pay @bob $20`

**Alice wants to get paid**
> Alice casts `@daimobot request @bob $20`
or
> `@daimobot request $20 from @bob`

**Comment by dcposch** [comment]
## Remaining issues

- Link preview not showing in created posts
- Bot doesn't reply on request completion

**Comment by dcposch** [comment]
Shipped
