### ISSUE TITLE
Scrolling on home screen resets spuriously

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#829]
https://github.com/daimo-eth/daimo/assets/6984346/b831fcc5-69a5-4fdb-bd14-70dae4762c47

**Comment by dcposch** [comment]
## Steps to reproduce

### Via history

- Open an account with long history
- Scroll down
- [Unexpected behavior] After a few seconds, it jumps back to top of history

### Via search

- Tap search bar
- Scroll down
- [Unexpected behavior] After a few seconds, it jumps back to top of history
