### ISSUE TITLE
Seed Phrase Backup option

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#868]
Users would like an alternative to passkey backups, two aims with seed phrase backup option:
- Communicate that Daimo is truly self custody, no strings attached -- even if this may be a rarely used feature, the presence can communicate the true your keys your coins / "You're in control" vibes if done well
- Give an alternative to users without passkeys
    - Passkeys are still in their infancy, many third party password managers don't support, and some OSes (like #482 ) don't work for passkey backups -- a seed phrase backup would ensure users can safely back up their account in that case.

**Comment by nalinbhardwaj** [comment]
Designs: https://www.figma.com/file/wBBNeEzlsObaE8A8i9iVf7/Daimo-iOS-App?type=design&node-id=4717-323&mode=design&t=w8WyHNE4ys119YwH-4

**Comment by dcposch** [comment]
Done ⚡️
