### ISSUE TITLE
Profile pictures might be bugged when they're just loaded?

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#879]
Hanna just connected Farcaster. Her picture doesn’t load on my phone: 

<img width="256" src="https://github.com/daimo-eth/daimo/assets/6984346/2f60943d-6ca0-4cc2-be5c-b4b0eddb0814">

Other report:
> I just invited someone, the FC profile pic visible on invite tab, but it doesn't show when sending money to the same person
Later:
> It's magically fixed now so no screenshots

Ideally fix it so it works, and we should put the default in these cases if not fixable

**Comment by dcposch** [comment]
Fixed in #905
