### ISSUE TITLE
Incident: ops reverting due to paymaster error

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#892]
## Summary

On Wed Mar 20, there was a big gas price spike on Base.

This made our top-up MetaPaymaster start reverting, causing all transactions to fail for 2:20m.

## Timeline

**2024-03-20, all times in Pacific time.**

| Time | Event |
|--------|--------|
| 15:46 | First failed transaction. Alert shows "missing or invalid parameters".  |
| 16:00 | Investigating. Tenderly says tx is valid, so we assumed RPC issue |
| 16:50 | Switch from Quicknode to Alchemy. Issue not fixed. |
| 17:22 | Deploy fix to bypass `eth_estimateGas` https://github.com/daimo-eth/daimo/pull/890 |
| 18:06 | Turn off metapaymaster in our paymaster. [Transaction](https://basescan.org/tx/0x1b7e2bb3f3f06dffac2f9e0c93dbfd77d3bc3201b1842929ec50d7051c30550c) | 
| 18:07 | Transactions working again. |

Total downtime: 2:20m

## Investigation

**The state of ethereum dev tooling is honestly atrocious.**

We could've solved this issue quickly with a correct error message.

- We use very standard, idiomatic way to run Ethereum transactions: viem's `writeContract` function.
- This calls `eth_estimateGas` under the hood, then `eth_sendTransaction`.
- At the start of the incident, our RPC provider started returning **`Missing or invalid parameters. Double check you have provided the correct parameters.`** However, the parameters passed to `eth_estimateGas` were well-formed and hadn't changed. (In hindsight: presumably the transaction was reverting in simulation.) The error message is useless and misleading, and made us suspect an RPC provider issue.
- Then, we tried verifying what was going on in Tenderly. **The same transactions succeeded in Tenderly.** Same from, to, and calldata. (Maybe they were simulating as of an out-of-date block, even though we specified latest.) We've seen erroneous transaction simulation results in Tenderly before. It is now banned, and we will not be using Tenderly for any purpose going forward.
- We used a fixed gas limit to bypass `eth_estimateGas`. This let us [see the bundle transaction revert onchain](https://basescan.org/tx/0x07a55b03e90b0c8fe555b2fb3ce76680ba5c66f7966b17ca0301a28643c2b022)... but with an equally useless **return data out of bounds** error.
- It looks like the 4337 EntryPoint 0.6 throws this low-level error, calling `RETURNDATACOPY` incorrectly, when a paymaster postOp reverts.
- We finally found the real error deep inside [this geth debug trace](https://basescan.org/vmtrace?txhash=0x07a55b03e90b0c8fe555b2fb3ce76680ba5c66f7966b17ca0301a28643c2b022&type=gethtrace2).

None of this particularly inspires confidence.

## Corrective actions

- [x] **Avoid calling `eth_estimateGas`.** This solved the incorrect error message above, and also decreases latency by removing one API-to-RPC roundtrip from our transaction time.
- [x] **Disable metapaymaster**. This solved the immediate issue.
- [x] **Link directly to a correct trace on every reverted op.** https://github.com/daimo-eth/daimo/issues/891

**Comment by nalinbhardwaj** [comment]
All 3 action items are done, closing.
