### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#909]
- Fix android, shows gradient circle logo in center instead of plain logo over color
- Make splash screen animated: rotate the vault circle of Daimo logo

**Comment by dcposch** [comment]
## Splash screen animation

### Current

![splash-screen](https://github.com/daimo-eth/daimo/assets/169280/6205aa6b-ae14-4000-acba-2327adeb72aa)

**Comment by dcposch** [comment]
Done for now. Can revisit animation in future.
