### ISSUE TITLE
onboarding checklist doesn't account for refreshing

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#933]
<img width="256" alt="image" src="https://github.com/daimo-eth/daimo/assets/6984346/c0e898a1-a5eb-47d3-9edd-d9c1867295b4">

**Comment by nalinbhardwaj** [comment]
<img width="565" alt="image" src="https://github.com/daimo-eth/daimo/assets/6984346/e9c83d1a-cd0e-4cf7-bd63-d775926474f4">

**Comment by dcposch** [comment]
Fixed
