### ISSUE TITLE
Upstream viem bug: tx chain ID != client chain ID

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#935]
seems to be due to https://github.com/wevm/viem/issues/1389 -- happened once so far. Either fix here or upstream PR.

**Comment by dcposch** [comment]
## Reoccurring with `publicClient` rather than `walletClient`

```
he contract function "balanceOf" returned no data ("0x").
This could be due to any of the following:
  - The contract does not have the function "balanceOf",
  - The parameters passed to the contract function may be invalid, or
  - The address is not a contract.
Contract Call:
  address:   0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913
  function:  balanceOf(address account)
  args:               (0xFBfa6A0D1F44b60d7CCA4b95d5a2CfB15246DB0D)
```

**Comment by nalinbhardwaj** [comment]
**Solved**: llamarpc web socket RPCs are broken, in an independent small script, using websocket llamarpc reliably produces incorrect Ethereum main net results in 1 out ~1000 queries. This resolves this issue -- occasionally, viem fallback transport would use that RPC and produce erroneous results.

Fixed in https://github.com/daimo-eth/daimo-infra/commit/139d1403d50c4b19d72e576c2d721c090c883487 by replacing all llamarpc usage by chainstack.
