### ISSUE TITLE
Support ERC 1271 Signature Validation

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#99]
If daimo accounts are ever used with dapps/contracts besides the current set written by us, they may depend on ERC1271 for Signature Validation, Implement a simple [`isValidSignature`](https://eips.ethereum.org/EIPS/eip-1271) to prevent them from breaking.

Example: https://github.com/eth-infinitism/account-abstraction/blob/5e78f8635552e3c55fbced072056a77c8f1e8b75/contracts/samples/gnosis/EIP4337Fallback.sol#L73

**Comment by dcposch** [comment]
done
