### ISSUE TITLE
Telegram support link

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#990]
## Goal

**Give users an easy way to contact us.** This is especially important if they ran into a bug or got confused.

## Proposed solution

We have a support tg now: https://t.me/daimo_support

Link to this in some tasteful way in at least two places:
- On the debug bottom sheet (for current look, see #481 ). We should explicitly invite people to send the Debug Log to our support tg.
- In-app somewhere, maybe the settings page?

And we might want to tell people about it at the end of onboarding. Eg on the Allow Notifs screen, "Questions? Issues? Reach us on Telegram <screenshot of button in settings tab>"

Finally, use Notion + super.so to link to it from https://daimo.com/support

All details TBD. Needs design.

**Comment by michelle-chiu** [comment]
Is this already resolved? I noticed we have this "Questions? Feedback?" section on the Settings page.

![IMG_8617](https://github.com/daimo-eth/daimo/assets/5884103/ae8c058c-0929-4960-a4ce-5488aecda746)

**Comment by dcposch** [comment]
yes--fixed in #1000
